sudo: required
services:
  - docker

# build test image for testing
before_install:
  - docker build -t lucasgmm20/react-test -f ./client/Dockerfile.dev ./client/

# test running section
script:
  - docker run -e CI=true lucasgmm20/react-test npm test -- --coverage

# for production
after_success:
  # build production images
  - docker build -t lucasgmm20/multi-client ./client
  - docker build -t lucasgmm20/multi-nginx ./nginx
  - docker build -t lucasgmm20/multi-server ./server
  - docker build -t lucasgmm20/multi-worker ./worker

  #  log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # pushes images to docker-hub
  - docker push lucasgmm20/multi-client
  - docker push lucasgmm20/multi-nginx
  - docker push lucasgmm20/multi-server
  - docker push lucasgmm20/multi-worker

# for deployment!
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-309613703225"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
